---
Name: search-elastic-config
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Search\Query\Facet\FacetAdaptor:
    class: SilverStripe\SearchElastic\Query\Facet\FacetAdaptor
  SilverStripe\Search\Query\Filter\CriteriaAdaptor:
    class: SilverStripe\SearchElastic\Query\Filter\CriteriaAdaptor
  SilverStripe\Search\Query\Filter\CriterionAdaptor:
    class: SilverStripe\SearchElastic\Query\Filter\CriterionAdaptor
  SilverStripe\Search\Service\SearchServiceAdaptor:
    class: SilverStripe\SearchElastic\Service\SearchServiceAdaptor
  Elastic\EnterpriseSearch\Client:
    factory: SilverStripe\SearchElastic\Service\ClientFactory
    constructor:
      host: '`ENTERPRISE_SEARCH_ENDPOINT`'
      token: '`ENTERPRISE_SEARCH_API_SEARCH_KEY`'
      http_client: '%$GuzzleHttp\Client'
