---
Name: search-elastic-config
---
SilverStripe\Search\Service\SearchService:
  index_variant: '`ENTERPRISE_SEARCH_ENGINE_PREFIX`'

SilverStripe\ElasticAppSearch\Service\AppSearchService:
  # Sets the index variant value. If using the silverstripe-search-service module, this must be the same as what you use for that (e.g. `ENTERPRISE_SEARCH_ENGINE_PREFIX` or `APP_SEARCH_ENGINE_PREFIX`)
  index_variant: '`ENTERPRISE_SEARCH_ENGINE_PREFIX`'
