---
Name: search-elastic-config
---
SilverStripe\Core\Injector\Injector:
  SilverStripe\Search\Service\SearchServiceAdaptor:
    class: SilverStripe\SearchElastic\Service\SearchServiceAdaptor
  Elastic\EnterpriseSearch\Client:
    factory: SilverStripe\SearchElastic\Service\ClientFactory
    constructor:
      host: '`ENTERPRISE_SEARCH_ENDPOINT`'
      token: '`ENTERPRISE_SEARCH_API_SEARCH_KEY`'
      http_client: '%$GuzzleHttp\Client'

SilverStripe\ElasticAppSearch\Service\AppSearchService:
  # Sets the index variant value. If using the silverstripe-search-service module, this must be the same as what you use for that (e.g. `ENTERPRISE_SEARCH_ENGINE_PREFIX` or `APP_SEARCH_ENGINE_PREFIX`)
  index_variant: '`ENTERPRISE_SEARCH_ENGINE_PREFIX`'
