name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ENTERPRISE_SEARCH_API_SEARCH_KEY: dummykey

jobs:
  ci:
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      # disable auto detection of JS tests (remove if any JS tests are added)
      js: false
